In [5]:
import numpy as np
calls=np.array([5,6,7,8,9,11])
print(calls)

[ 5  6  7  8  9 11]


In [8]:
#multi dimension

multi=np.array([["Jan","Feb","Mar"],
               [300,400,500],
               [600,700,800],
               [6,7,8]])
print(multi)

[['Jan' 'Feb' 'Mar']
 ['300' '400' '500']
 ['600' '700' '800']
 ['6' '7' '8']]


In [ ]:
multi=np.array([["Jan","Feb","Mar"],
               [300,400,500],
               [600,700,800],
               [6,7,8]])
print(multi.shape)   #   .shape gives the no.of rows and columns

(4, 3)


In [10]:
multi[1][2]

np.str_('500')

In [13]:
multi[:,2]

array(['Mar', '500', '800', '8'], dtype='<U21')

In [15]:
multi[2:,2]

array(['800', '8'], dtype='<U21')

In [16]:
multi[:,1]

array(['Feb', '400', '700', '7'], dtype='<U21')

BOOLEAN FILTERING

In [17]:
s_r=np.array([3.6,4,2,3,1])
s_r[s_r>3]

array([3.6, 4. ])

In [30]:
s_r[s_r>3]

array([3.6, 4. ])

In [26]:
s_r[(s_r>=2)&(s_r<=4)]

array([3.6, 4. , 2. , 3. ])

In [28]:
np.sum(calls)

np.int64(46)

In [ ]:
print(np.mean(calls))
print(np.max(calls))
print(np.min(calls))
print(np.std(calls))

7.666666666666667
11
5
1.9720265943665387


In [33]:
North=np.array([5,100,30])
South=np.array([3,2,5])
np.concatenate((North,South))

array([  5, 100,  30,   3,   2,   5])