In [2]:
import numpy as np
calls=np.array([5,6,7,8,9,11])
print(calls)

[ 5  6  7  8  9 11]


In [8]:
#multi dimension

multi=np.array([["Jan","Feb","Mar"],
               [300,400,500],
               [600,700,800],
               [6,7,8]])
print(multi)

[['Jan' 'Feb' 'Mar']
 ['300' '400' '500']
 ['600' '700' '800']
 ['6' '7' '8']]


In [ ]:
multi=np.array([["Jan","Feb","Mar"],
               [300,400,500],
               [600,700,800],
               [6,7,8]])
print(multi.shape)   #   .shape gives the no.of rows and columns

(4, 3)


In [10]:
multi[1][2]

np.str_('500')

In [13]:
multi[:,2]

array(['Mar', '500', '800', '8'], dtype='<U21')

In [15]:
multi[2:,2]

array(['800', '8'], dtype='<U21')

In [16]:
multi[:,1]

array(['Feb', '400', '700', '7'], dtype='<U21')

BOOLEAN FILTERING

In [17]:
s_r=np.array([3.6,4,2,3,1])
s_r[s_r>3]

array([3.6, 4. ])

In [30]:
s_r[s_r>3]

array([3.6, 4. ])

In [26]:
s_r[(s_r>=2)&(s_r<=4)]

array([3.6, 4. , 2. , 3. ])

In [28]:
np.sum(calls)

np.int64(46)

In [ ]:
print(np.mean(calls))
print(np.max(calls))
print(np.min(calls))
print(np.std(calls))

7.666666666666667
11
5
1.9720265943665387


In [33]:
North=np.array([5,100,30])
South=np.array([3,2,5])
np.concatenate((North,South))

array([  5, 100,  30,   3,   2,   5])

In [ ]:
cd=np.array([132,13,15,102])
[(np.where(cd==15))]   #gives the index

[(array([2]),)]

In [ ]:
cd=np.array([132,13,15,102])
cd[(np.where(cd==15))]  # gives the actual value by giving variable name

In [13]:
cs=np.array([["cus_id","rtng"],
            ["cus101",3],
            ["cus102",4.5],
            ["cus103",4.0],
            ["cus104",4.2],
            ["cus105",4.0]])
print(cs)


[['cus_id' 'rtng']
 ['cus101' '3']
 ['cus102' '4.5']
 ['cus103' '4.0']
 ['cus104' '4.2']
 ['cus105' '4.0']]


In [44]:
cs[(np.where(cs>=4))]

UFuncTypeError: ufunc 'greater_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>) -> None

In [35]:
np.sort(cs[1:,1])[::-1]

array(['4.5', '4.2', '4.0', '4.0', '3'], dtype='<U32')

In [51]:
call_duration=np.array([5,7,10,15,6,9,12,8])
satisfacation=np.array([5,4,3,5,2,4,5,3])
calls=np.array([120,130,160,180,150,170,140,200])

#average call duration
print(np.average(call_duration))
#maximum satisfacation
print(np.max(satisfacation))
#calls greater than 150
print(calls[np.where(calls>150)])
#sort call duration
np.sort(call_duration)
#satisfacation is 5
np.where(satisfacation==5)


9.0
5
[160 180 170 200]


(array([0, 3, 6]),)